### ISSUE TITLE
Turing Machine combined left-side outputs

### ISSUE THREAD

**Issue by MarcBoule** [stellare-modular/vcv-rack#6]
Hi, in the hardware Turing Machine , the combined outputs on the left side, 
i.e. 1+2,  2+4,  4+7  and  1+2+4+7,
are used to output an AND-gate combination of the 1 to 7 signals. However, in the software version, it instead seems to be an OR-gate behavior. Is this difference intended, as I believe the Rack port is intended to be a faithful clone of the hardware version. I really like this module by the way, when I'm running on low in terms of creativity for a melody, it's a wonderful tool! Cheers!

**Comment by n6smith** [comment]
Confirmed.. There is a variance with the hardware versions due to the combination Gate/Trigger outputs being OR'd instead of AND'd resulting in the combination outputs producing more frequent gate/triggers than the single outputs... rather than less frequent as is the case with the original Turing Machine Hardware.

**Comment by sanderbaan** [comment]
Fixed in 0.6 release

**Comment by MarcBoule** [comment]
Thanks for the fix!
